# Generated by Django 2.2.5 on 2020-06-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='판매자',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='프로필_사진',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
