# Generated by Django 2.2.5 on 2020-06-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200618_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='기타사항',
        ),
    ]
