# Generated by Django 2.2.5 on 2020-06-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200618_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='프로필사진',
            new_name='프로필_사진',
        ),
    ]
