# Generated by Django 2.2.5 on 2020-06-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200618_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('korean', '한국어'), ('chinese', 'Chinese')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='생일',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='기타사항',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='성별',
            field=models.CharField(blank=True, choices=[('male', '남자'), ('female', '여자'), ('other', '기타')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='프로필_사진',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
