# Generated by Django 2.2.5 on 2020-06-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_통화'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='할인_혜택_회원',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='통화',
            field=models.CharField(blank=True, choices=[('usd', 'USD $'), ('krw', 'KRW 원')], max_length=7, null=True),
        ),
    ]
