# Generated by Django 2.2.5 on 2020-06-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200620_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='guest',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='room',
            new_name='product',
        ),
    ]
