# Generated by Django 2.2.5 on 2020-06-20 08:23

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('등록한_날짜', models.DateTimeField(auto_now_add=True)),
                ('수정한_날짜', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('등록한_날짜', models.DateTimeField(auto_now_add=True)),
                ('수정한_날짜', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=150)),
                ('file', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('등록한_날짜', models.DateTimeField(auto_now_add=True)),
                ('수정한_날짜', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Product Type',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('등록한_날짜', models.DateTimeField(auto_now_add=True)),
                ('수정한_날짜', models.DateTimeField(auto_now=True)),
                ('제품이름', models.CharField(max_length=140)),
                ('설명', models.TextField()),
                ('국가', django_countries.fields.CountryField(max_length=2)),
                ('도로명_주소', models.CharField(max_length=80)),
                ('상세주소', models.CharField(max_length=150)),
                ('가격', models.IntegerField()),
                ('할인_혜택_고객용_가격', models.IntegerField()),
                ('남은_수량', models.IntegerField()),
                ('규격_및_중량', models.CharField(max_length=80)),
                ('원산지', models.CharField(max_length=80)),
                ('무료배송', models.BooleanField(default=False)),
                ('생산날짜', models.TimeField()),
                ('유통기한', models.TimeField()),
                ('facilities', models.ManyToManyField(blank=True, related_name='products', to='products.Facility')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
