# Generated by Django 2.2.5 on 2020-06-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200620_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='product_photos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='제품_종류',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.ProductType'),
        ),
    ]
